# -*- coding: utf-8 -*-
"""Placement_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IFGujTLFmuICc8WvA9hMrHMUA7AlXstq
"""

import numpy as np
import pandas as pd

"""##Step1. Reading the dataset

"""

df=pd.read_csv('/placement.csv')

"""##Step2. Preprocessing + EDA + Feature Selection"""

df.head()

df.info()

df.shape

df=df.iloc[:,1:]

df.head()

import matplotlib.pyplot as plt

plt.scatter(df['cgpa'],df['iq'],c=df['placement'])

x=df.iloc[:,0:2]
y=df.iloc[:,-1]

x

y.shape

"""##Step3. Extract input and output columns"""

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1)
x_train

x_test

y_train

"""##Step4. Scale the values between -1 to 1"""

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_train

"""##Step5.Train the test split and model"""

x_test=scaler.transform(x_test)
x_test

"""##Step6. Evaluate the model and model Selection"""

from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)
y_test

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

from mlxtend.plotting import plot_decision_regions
plot_decision_regions(x_train,y_train.values,clf=model, legend=2)

import pickle
pickle.dump(model,open('model.pkl','wb'))